language: c++
dist: bionic
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -y scons

defore_script:
  - git clone https://github.com/xanthospap/ggdatetime.git && cd ggdatetime
  - mv src/Makefile.am.production src/Makefile.am
  - scons
  - sudo scons install
  - cd ../
  - sudo ldconfig

script:
  - scons
